# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/bskyrb/all/bskyrb.rbi
#
# bskyrb-0.5.3

module Bskyrb
  include Atmosfire
end
class Bskyrb::Error < StandardError
end
class Bskyrb::HTTPError < Bskyrb::Error
end
class Bskyrb::UnauthorizedError < Bskyrb::HTTPError
end
