# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/bskyrb/all/bskyrb.rbi
#
# bskyrb-0.5.1

module Bskyrb
end
module Bskyrb::LexiconParser
  def self.basic_class_definitions(classes_hash); end
  def self.basic_template; end
  def self.build_class_hash_from_schema(json_schema, output = nil); end
  def self.build_classes_hash_from_lexicon_defs(lexicon_file); end
  def self.build_queries_and_procedures_from_lexicon(lexicon_file); end
  def self.def_is_procedure(defn); end
  def self.def_is_query(defn); end
  def self.def_is_subscription(defn); end
  def self.input_output_class_definitions(classes_hash); end
  def self.input_output_template; end
  def self.ref_to_class_str(ref, ns = nil); end
end
class Bskyrb::DynamicClassFromHash
  def self.from_hash(hash); end
end
