# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/xrpc/all/xrpc.rbi
#
# xrpc-0.1.5

module XRPC
  def self.client(url); end
end
class XRPC::Client
  def get; end
  def initialize(base_url, token = nil); end
  def post; end
end
class XRPC::Client::GetRequest
  def initialize(base_url, headers); end
  def method_missing(method_name, **params); end
  def self.default_cookies; end
  def self.default_cookies=(arg0); end
  def self.default_options; end
  def self.default_options=(arg0); end
  extend HTTParty::ClassMethods
  extend HTTParty::ModuleInheritableAttributes::ClassMethods
  include HTTParty
  include HTTParty::ModuleInheritableAttributes
end
class XRPC::Client::PostRequest
  def initialize(base_url, headers); end
  def method_missing(method_name, **params); end
  def self.default_cookies; end
  def self.default_cookies=(arg0); end
  def self.default_options; end
  def self.default_options=(arg0); end
  extend HTTParty::ClassMethods
  extend HTTParty::ModuleInheritableAttributes::ClassMethods
  include HTTParty
  include HTTParty::ModuleInheritableAttributes
end
