module Bskyrb
  module RequestUtils
    def default_headers: -> Hash[String, String]
    def create_record_uri: (String) -> URI
  end

  class Credentials
    @username: String
    @pw: String

    def initialize: (String, String) -> void
  end

  class Session
    @credentials: Bskyrb::Credentials
    @pds: String
    @access_token: String
    @refresh_token: String

    def initialize: (Bskyrb::Credentials, String, Boolean) -> void
    def open!: -> void
  end
end
