module Bskyrb
  VERSION: String

  module RequestUtils
    def default_headers: -> Hash[String, String]
    def create_record_uri: (String) -> URI
    def default_authenticated_headers: (Session session) -> Hash[(String | Symbol), String]
  end

  class Credentials
    attr_reader username: String
    attr_reader pw: String

    def initialize: (String, String) -> void
  end

  class Session
    include Bskyrb::RequestUtils

    attr_reader credentials: Bskyrb::Credentials
    attr_reader pds: String
    attr_reader access_token: String
    attr_reader refresh_token: String
    attr_reader did: String

    def initialize: (Bskyrb::Credentials, String, ?bool) -> void
    def open!: -> void
  end

  class SkylineManager
    include RequestUtils

    attr_reader session: Session

    def initialize: (Session session) -> void
  end
end

module HTTParty
  class Response
    def []: (String | Symbol) -> untyped
  end
end
