module Bskyrb
  module AppBskyActorDefs
    class ProfileViewBasic
      attr_accessor did: untyped

      attr_accessor handle: untyped

      attr_accessor displayName: untyped

      attr_accessor avatar: untyped

      attr_accessor viewer: untyped

      attr_accessor labels: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyActorDefs
    class ProfileView
      attr_accessor did: untyped

      attr_accessor handle: untyped

      attr_accessor displayName: untyped

      attr_accessor description: untyped

      attr_accessor avatar: untyped

      attr_accessor indexedAt: untyped

      attr_accessor viewer: untyped

      attr_accessor labels: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyActorDefs
    class ProfileViewDetailed
      attr_accessor did: untyped

      attr_accessor handle: untyped

      attr_accessor displayName: untyped

      attr_accessor description: untyped

      attr_accessor avatar: untyped

      attr_accessor banner: untyped

      attr_accessor followersCount: untyped

      attr_accessor followsCount: untyped

      attr_accessor postsCount: untyped

      attr_accessor indexedAt: untyped

      attr_accessor viewer: untyped

      attr_accessor labels: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyActorDefs
    class ViewerState
      attr_accessor muted: untyped

      attr_accessor mutedByList: untyped

      attr_accessor blockedBy: untyped

      attr_accessor blocking: untyped

      attr_accessor following: untyped

      attr_accessor followedBy: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyActorDefs
    class Preferences
      attr_accessor items: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyActorDefs
    class AdultContentPref
      attr_accessor enabled: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyActorDefs
    class ContentLabelPref
      attr_accessor label: untyped

      attr_accessor visibility: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyActorDefs
    class SavedFeedsPref
      attr_accessor pinned: untyped

      attr_accessor saved: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyEmbedExternal
    class External
      attr_accessor uri: untyped

      attr_accessor title: untyped

      attr_accessor description: untyped

      attr_accessor thumb: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyEmbedExternal
    class View
      attr_accessor external: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyEmbedExternal
    class ViewExternal
      attr_accessor uri: untyped

      attr_accessor title: untyped

      attr_accessor description: untyped

      attr_accessor thumb: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyEmbedImages
    class Image
      attr_accessor image: untyped

      attr_accessor alt: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyEmbedImages
    class View
      attr_accessor images: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyEmbedImages
    class ViewImage
      attr_accessor thumb: untyped

      attr_accessor fullsize: untyped

      attr_accessor alt: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyEmbedRecord
    class View
      attr_accessor record: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyEmbedRecord
    class ViewRecord
      attr_accessor uri: untyped

      attr_accessor cid: untyped

      attr_accessor author: untyped

      attr_accessor value: untyped

      attr_accessor labels: untyped

      attr_accessor embeds: untyped

      attr_accessor indexedAt: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyEmbedRecord
    class ViewNotFound
      attr_accessor uri: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyEmbedRecord
    class ViewBlocked
      attr_accessor uri: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyEmbedRecordwithmedia
    class View
      attr_accessor record: untyped

      attr_accessor media: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedDefs
    class PostView
      attr_accessor uri: untyped

      attr_accessor cid: untyped

      attr_accessor author: untyped

      attr_accessor record: untyped

      attr_accessor embed: untyped

      attr_accessor replyCount: untyped

      attr_accessor repostCount: untyped

      attr_accessor likeCount: untyped

      attr_accessor indexedAt: untyped

      attr_accessor viewer: untyped

      attr_accessor labels: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedDefs
    class ViewerState
      attr_accessor repost: untyped

      attr_accessor like: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedDefs
    class FeedViewPost
      attr_accessor post: untyped

      attr_accessor reply: untyped

      attr_accessor reason: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedDefs
    class ReplyRef
      attr_accessor root: untyped

      attr_accessor parent: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedDefs
    class ReasonRepost
      attr_accessor by: untyped

      attr_accessor indexedAt: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedDefs
    class ThreadViewPost
      attr_accessor post: untyped

      attr_accessor parent: untyped

      attr_accessor replies: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedDefs
    class NotFoundPost
      attr_accessor uri: untyped

      attr_accessor notFound: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedDefs
    class BlockedPost
      attr_accessor uri: untyped

      attr_accessor blocked: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedDefs
    class GeneratorView
      attr_accessor uri: untyped

      attr_accessor cid: untyped

      attr_accessor did: untyped

      attr_accessor creator: untyped

      attr_accessor displayName: untyped

      attr_accessor description: untyped

      attr_accessor descriptionFacets: untyped

      attr_accessor avatar: untyped

      attr_accessor likeCount: untyped

      attr_accessor viewer: untyped

      attr_accessor indexedAt: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedDefs
    class GeneratorViewerState
      attr_accessor like: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedDefs
    class SkeletonFeedPost
      attr_accessor post: untyped

      attr_accessor reason: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedDefs
    class SkeletonReasonRepost
      attr_accessor repost: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedDescribefeedgenerator
    class Feed
      attr_accessor uri: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedDescribefeedgenerator
    class Links
      attr_accessor privacyPolicy: untyped

      attr_accessor termsOfService: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedGetlikes
    class Like
      attr_accessor indexedAt: untyped

      attr_accessor createdAt: untyped

      attr_accessor actor: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedPost
    class ReplyRef
      attr_accessor root: untyped

      attr_accessor parent: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedPost
    class Entity
      attr_accessor index: untyped

      attr_accessor value: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyFeedPost
    class TextSlice
      attr_accessor start: untyped

      attr_accessor end: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyGraphDefs
    class ListViewBasic
      attr_accessor uri: untyped

      attr_accessor cid: untyped

      attr_accessor name: untyped

      attr_accessor purpose: untyped

      attr_accessor avatar: untyped

      attr_accessor viewer: untyped

      attr_accessor indexedAt: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyGraphDefs
    class ListView
      attr_accessor uri: untyped

      attr_accessor cid: untyped

      attr_accessor creator: untyped

      attr_accessor name: untyped

      attr_accessor purpose: untyped

      attr_accessor description: untyped

      attr_accessor descriptionFacets: untyped

      attr_accessor avatar: untyped

      attr_accessor viewer: untyped

      attr_accessor indexedAt: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyGraphDefs
    class ListItemView
      attr_accessor subject: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyGraphDefs
    class ListPurpose
      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyGraphDefs
    class Modlist
      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyGraphDefs
    class ListViewerState
      attr_accessor muted: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyNotificationListnotifications
    class Notification
      attr_accessor uri: untyped

      attr_accessor cid: untyped

      attr_accessor author: untyped

      attr_accessor reason: untyped

      attr_accessor reasonSubject: untyped

      attr_accessor record: untyped

      attr_accessor isRead: untyped

      attr_accessor indexedAt: untyped

      attr_accessor labels: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyRichtextFacet
    class Mention
      attr_accessor did: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyRichtextFacet
    class Link
      attr_accessor uri: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyRichtextFacet
    class ByteSlice
      attr_accessor byteStart: untyped

      attr_accessor byteEnd: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class ActionView
      attr_accessor id: untyped

      attr_accessor action: untyped

      attr_accessor subject: untyped

      attr_accessor subjectBlobCids: untyped

      attr_accessor createLabelVals: untyped

      attr_accessor negateLabelVals: untyped

      attr_accessor reason: untyped

      attr_accessor createdBy: untyped

      attr_accessor createdAt: untyped

      attr_accessor reversal: untyped

      attr_accessor resolvedReportIds: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class ActionViewDetail
      attr_accessor id: untyped

      attr_accessor action: untyped

      attr_accessor subject: untyped

      attr_accessor subjectBlobs: untyped

      attr_accessor createLabelVals: untyped

      attr_accessor negateLabelVals: untyped

      attr_accessor reason: untyped

      attr_accessor createdBy: untyped

      attr_accessor createdAt: untyped

      attr_accessor reversal: untyped

      attr_accessor resolvedReports: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class ActionViewCurrent
      attr_accessor id: untyped

      attr_accessor action: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class ActionReversal
      attr_accessor reason: untyped

      attr_accessor createdBy: untyped

      attr_accessor createdAt: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class ActionType
      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class Takedown
      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class Flag
      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class Acknowledge
      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class Escalate
      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class ReportView
      attr_accessor id: untyped

      attr_accessor reasonType: untyped

      attr_accessor reason: untyped

      attr_accessor subjectRepoHandle: untyped

      attr_accessor subject: untyped

      attr_accessor reportedBy: untyped

      attr_accessor createdAt: untyped

      attr_accessor resolvedByActionIds: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class ReportViewDetail
      attr_accessor id: untyped

      attr_accessor reasonType: untyped

      attr_accessor reason: untyped

      attr_accessor subject: untyped

      attr_accessor reportedBy: untyped

      attr_accessor createdAt: untyped

      attr_accessor resolvedByActions: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class RepoView
      attr_accessor did: untyped

      attr_accessor handle: untyped

      attr_accessor email: untyped

      attr_accessor relatedRecords: untyped

      attr_accessor indexedAt: untyped

      attr_accessor moderation: untyped

      attr_accessor invitedBy: untyped

      attr_accessor invitesDisabled: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class RepoViewDetail
      attr_accessor did: untyped

      attr_accessor handle: untyped

      attr_accessor email: untyped

      attr_accessor relatedRecords: untyped

      attr_accessor indexedAt: untyped

      attr_accessor moderation: untyped

      attr_accessor labels: untyped

      attr_accessor invitedBy: untyped

      attr_accessor invites: untyped

      attr_accessor invitesDisabled: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class RepoViewNotFound
      attr_accessor did: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class RepoRef
      attr_accessor did: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class RecordView
      attr_accessor uri: untyped

      attr_accessor cid: untyped

      attr_accessor value: untyped

      attr_accessor blobCids: untyped

      attr_accessor indexedAt: untyped

      attr_accessor moderation: untyped

      attr_accessor repo: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class RecordViewDetail
      attr_accessor uri: untyped

      attr_accessor cid: untyped

      attr_accessor value: untyped

      attr_accessor blobs: untyped

      attr_accessor labels: untyped

      attr_accessor indexedAt: untyped

      attr_accessor moderation: untyped

      attr_accessor repo: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class RecordViewNotFound
      attr_accessor uri: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class Moderation
      attr_accessor currentAction: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class ModerationDetail
      attr_accessor currentAction: untyped

      attr_accessor actions: untyped

      attr_accessor reports: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class BlobView
      attr_accessor cid: untyped

      attr_accessor mimeType: untyped

      attr_accessor size: untyped

      attr_accessor createdAt: untyped

      attr_accessor details: untyped

      attr_accessor moderation: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class ImageDetails
      attr_accessor width: untyped

      attr_accessor height: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoAdminDefs
    class VideoDetails
      attr_accessor width: untyped

      attr_accessor height: untyped

      attr_accessor length: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoLabelDefs
    class Label
      attr_accessor src: untyped

      attr_accessor uri: untyped

      attr_accessor cid: untyped

      attr_accessor val: untyped

      attr_accessor neg: untyped

      attr_accessor cts: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoLabelSubscribelabels
    class Labels
      attr_accessor seq: untyped

      attr_accessor labels: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoLabelSubscribelabels
    class Info
      attr_accessor name: untyped

      attr_accessor message: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoModerationDefs
    class ReasonType
      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoModerationDefs
    class ReasonSpam
      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoModerationDefs
    class ReasonViolation
      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoModerationDefs
    class ReasonMisleading
      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoModerationDefs
    class ReasonSexual
      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoModerationDefs
    class ReasonRude
      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoModerationDefs
    class ReasonOther
      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoRepoApplywrites
    class Create
      attr_accessor collection: untyped

      attr_accessor rkey: untyped

      attr_accessor value: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoRepoApplywrites
    class Update
      attr_accessor collection: untyped

      attr_accessor rkey: untyped

      attr_accessor value: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoRepoApplywrites
    class Delete
      attr_accessor collection: untyped

      attr_accessor rkey: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoRepoListrecords
    class Record
      attr_accessor uri: untyped

      attr_accessor cid: untyped

      attr_accessor value: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoServerCreateapppassword
    class AppPassword
      attr_accessor name: untyped

      attr_accessor password: untyped

      attr_accessor createdAt: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoServerCreateinvitecodes
    class AccountCodes
      attr_accessor account: untyped

      attr_accessor codes: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoServerDefs
    class InviteCode
      attr_accessor code: untyped

      attr_accessor available: untyped

      attr_accessor disabled: untyped

      attr_accessor forAccount: untyped

      attr_accessor createdBy: untyped

      attr_accessor createdAt: untyped

      attr_accessor uses: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoServerDefs
    class InviteCodeUse
      attr_accessor usedBy: untyped

      attr_accessor usedAt: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoServerDescribeserver
    class Links
      attr_accessor privacyPolicy: untyped

      attr_accessor termsOfService: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoServerListapppasswords
    class AppPassword
      attr_accessor name: untyped

      attr_accessor createdAt: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoSyncListrepos
    class Repo
      attr_accessor did: untyped

      attr_accessor head: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoSyncSubscriberepos
    class Commit
      attr_accessor seq: untyped

      attr_accessor rebase: untyped

      attr_accessor tooBig: untyped

      attr_accessor repo: untyped

      attr_accessor commit: untyped

      attr_accessor prev: untyped

      attr_accessor blocks: untyped

      attr_accessor ops: untyped

      attr_accessor blobs: untyped

      attr_accessor time: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoSyncSubscriberepos
    class Handle
      attr_accessor seq: untyped

      attr_accessor did: untyped

      attr_accessor handle: untyped

      attr_accessor time: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoSyncSubscriberepos
    class Migrate
      attr_accessor seq: untyped

      attr_accessor did: untyped

      attr_accessor migrateTo: untyped

      attr_accessor time: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoSyncSubscriberepos
    class Tombstone
      attr_accessor seq: untyped

      attr_accessor did: untyped

      attr_accessor time: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoSyncSubscriberepos
    class Info
      attr_accessor name: untyped

      attr_accessor message: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module ComAtprotoSyncSubscriberepos
    class RepoOp
      attr_accessor action: untyped

      attr_accessor path: untyped

      attr_accessor cid: untyped

      def self.from_hash: (untyped hash) -> untyped
    end
  end

  module AppBskyActorGetpreferences
    module GetPreferences
      class Input
        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[untyped, untyped]
      end

      class Output
        attr_accessor preferences: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyActorGetprofile
    module GetProfile
      class Input
        attr_accessor actor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[untyped, untyped]
      end
    end
  end

  module AppBskyActorGetprofiles
    module GetProfiles
      class Input
        attr_accessor actors: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor profiles: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyActorGetsuggestions
    module GetSuggestions
      class Input
        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor actors: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyActorPutpreferences
    module PutPreferences
      class Input
        attr_accessor preferences: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyActorSearchactors
    module SearchActors
      class Input
        attr_accessor term: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor actors: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyActorSearchactorstypeahead
    module SearchActorsTypeahead
      class Input
        attr_accessor term: untyped

        attr_accessor limit: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor actors: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyFeedDescribefeedgenerator
    module DescribeFeedGenerator
      class Output
        attr_accessor did: untyped

        attr_accessor feeds: untyped

        attr_accessor links: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyFeedGetactorfeeds
    module GetActorFeeds
      class Input
        attr_accessor actor: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor feeds: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyFeedGetauthorfeed
    module GetAuthorFeed
      class Input
        attr_accessor actor: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor feed: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyFeedGetfeed
    module GetFeed
      class Input
        attr_accessor feed: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor feed: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyFeedGetfeedgenerator
    module GetFeedGenerator
      class Input
        attr_accessor feed: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor view: untyped

        attr_accessor isOnline: untyped

        attr_accessor isValid: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyFeedGetfeedgenerators
    module GetFeedGenerators
      class Input
        attr_accessor feeds: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor feeds: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyFeedGetfeedskeleton
    module GetFeedSkeleton
      class Input
        attr_accessor feed: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor feed: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyFeedGetlikes
    module GetLikes
      class Input
        attr_accessor uri: untyped

        attr_accessor cid: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor uri: untyped

        attr_accessor cid: untyped

        attr_accessor cursor: untyped

        attr_accessor likes: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyFeedGetpostthread
    module GetPostThread
      class Input
        attr_accessor uri: untyped

        attr_accessor depth: untyped

        attr_accessor parentHeight: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor thread: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyFeedGetposts
    module GetPosts
      class Input
        attr_accessor uris: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor posts: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyFeedGetrepostedby
    module GetRepostedBy
      class Input
        attr_accessor uri: untyped

        attr_accessor cid: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor uri: untyped

        attr_accessor cid: untyped

        attr_accessor cursor: untyped

        attr_accessor repostedBy: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyFeedGettimeline
    module GetTimeline
      class Input
        attr_accessor algorithm: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor feed: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyGraphGetblocks
    module GetBlocks
      class Input
        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor blocks: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyGraphGetfollowers
    module GetFollowers
      class Input
        attr_accessor actor: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor subject: untyped

        attr_accessor cursor: untyped

        attr_accessor followers: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyGraphGetfollows
    module GetFollows
      class Input
        attr_accessor actor: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor subject: untyped

        attr_accessor cursor: untyped

        attr_accessor follows: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyGraphGetlist
    module GetList
      class Input
        attr_accessor list: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor list: untyped

        attr_accessor items: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyGraphGetlistmutes
    module GetListMutes
      class Input
        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor lists: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyGraphGetlists
    module GetLists
      class Input
        attr_accessor actor: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor lists: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyGraphGetmutes
    module GetMutes
      class Input
        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor mutes: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyGraphMuteactor
    module MuteActor
      class Input
        attr_accessor actor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyGraphMuteactorlist
    module MuteActorList
      class Input
        attr_accessor list: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyGraphUnmuteactor
    module UnmuteActor
      class Input
        attr_accessor actor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyGraphUnmuteactorlist
    module UnmuteActorList
      class Input
        attr_accessor list: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyNotificationGetunreadcount
    module GetUnreadCount
      class Input
        attr_accessor seenAt: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor count: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyNotificationListnotifications
    module ListNotifications
      class Input
        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        attr_accessor seenAt: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor notifications: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyNotificationUpdateseen
    module UpdateSeen
      class Input
        attr_accessor seenAt: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyUnspeccedGetpopular
    module GetPopular
      class Input
        attr_accessor includeNsfw: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor feed: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module AppBskyUnspeccedGetpopularfeedgenerators
    module GetPopularFeedGenerators
      class Output
        attr_accessor feeds: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoAdminDisableaccountinvites
    module DisableAccountInvites
      class Input
        attr_accessor account: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoAdminDisableinvitecodes
    module DisableInviteCodes
      class Input
        attr_accessor codes: untyped

        attr_accessor accounts: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoAdminEnableaccountinvites
    module EnableAccountInvites
      class Input
        attr_accessor account: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoAdminGetinvitecodes
    module GetInviteCodes
      class Input
        attr_accessor sort: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor codes: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoAdminGetmoderationaction
    module GetModerationAction
      class Input
        attr_accessor id: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[untyped, untyped]
      end
    end
  end

  module ComAtprotoAdminGetmoderationactions
    module GetModerationActions
      class Input
        attr_accessor subject: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor actions: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoAdminGetmoderationreport
    module GetModerationReport
      class Input
        attr_accessor id: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[untyped, untyped]
      end
    end
  end

  module ComAtprotoAdminGetmoderationreports
    module GetModerationReports
      class Input
        attr_accessor subject: untyped

        attr_accessor ignoreSubjects: untyped

        attr_accessor reporters: untyped

        attr_accessor resolved: untyped

        attr_accessor actionType: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        attr_accessor reverse: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor reports: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoAdminGetrecord
    module GetRecord
      class Input
        attr_accessor uri: untyped

        attr_accessor cid: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[untyped, untyped]
      end
    end
  end

  module ComAtprotoAdminGetrepo
    module GetRepo
      class Input
        attr_accessor did: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[untyped, untyped]
      end
    end
  end

  module ComAtprotoAdminRebaserepo
    module RebaseRepo
      class Input
        attr_accessor repo: untyped

        attr_accessor swapCommit: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoAdminResolvemoderationreports
    module ResolveModerationReports
      class Input
        attr_accessor actionId: untyped

        attr_accessor reportIds: untyped

        attr_accessor createdBy: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[untyped, untyped]
      end
    end
  end

  module ComAtprotoAdminReversemoderationaction
    module ReverseModerationAction
      class Input
        attr_accessor id: untyped

        attr_accessor reason: untyped

        attr_accessor createdBy: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[untyped, untyped]
      end
    end
  end

  module ComAtprotoAdminSearchrepos
    module SearchRepos
      class Input
        attr_accessor term: untyped

        attr_accessor invitedBy: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor repos: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoAdminTakemoderationaction
    module TakeModerationAction
      class Input
        attr_accessor action: untyped

        attr_accessor subject: untyped

        attr_accessor subjectBlobCids: untyped

        attr_accessor createLabelVals: untyped

        attr_accessor negateLabelVals: untyped

        attr_accessor reason: untyped

        attr_accessor createdBy: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[untyped, untyped]
      end
    end
  end

  module ComAtprotoAdminUpdateaccountemail
    module UpdateAccountEmail
      class Input
        attr_accessor account: untyped

        attr_accessor email: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoAdminUpdateaccounthandle
    module UpdateAccountHandle
      class Input
        attr_accessor did: untyped

        attr_accessor handle: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoIdentityResolvehandle
    module ResolveHandle
      class Input
        attr_accessor handle: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor did: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoIdentityUpdatehandle
    module UpdateHandle
      class Input
        attr_accessor handle: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoLabelQuerylabels
    module QueryLabels
      class Input
        attr_accessor uriPatterns: untyped

        attr_accessor sources: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor labels: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoModerationCreatereport
    module CreateReport
      class Input
        attr_accessor reasonType: untyped

        attr_accessor reason: untyped

        attr_accessor subject: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor id: untyped

        attr_accessor reasonType: untyped

        attr_accessor reason: untyped

        attr_accessor subject: untyped

        attr_accessor reportedBy: untyped

        attr_accessor createdAt: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoRepoApplywrites
    module ApplyWrites
      class Input
        attr_accessor repo: untyped

        attr_accessor validate: untyped

        attr_accessor writes: untyped

        attr_accessor swapCommit: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoRepoCreaterecord
    module CreateRecord
      class Input
        attr_accessor repo: untyped

        attr_accessor collection: untyped

        attr_accessor rkey: untyped

        attr_accessor validate: untyped

        attr_accessor record: untyped

        attr_accessor swapCommit: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor uri: untyped

        attr_accessor cid: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoRepoDeleterecord
    module DeleteRecord
      class Input
        attr_accessor repo: untyped

        attr_accessor collection: untyped

        attr_accessor rkey: untyped

        attr_accessor swapRecord: untyped

        attr_accessor swapCommit: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoRepoDescriberepo
    module DescribeRepo
      class Input
        attr_accessor repo: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor handle: untyped

        attr_accessor did: untyped

        attr_accessor didDoc: untyped

        attr_accessor collections: untyped

        attr_accessor handleIsCorrect: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoRepoGetrecord
    module GetRecord
      class Input
        attr_accessor repo: untyped

        attr_accessor collection: untyped

        attr_accessor rkey: untyped

        attr_accessor cid: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor uri: untyped

        attr_accessor cid: untyped

        attr_accessor value: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoRepoListrecords
    module ListRecords
      class Input
        attr_accessor repo: untyped

        attr_accessor collection: untyped

        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        attr_accessor rkeyStart: untyped

        attr_accessor rkeyEnd: untyped

        attr_accessor reverse: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor records: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoRepoPutrecord
    module PutRecord
      class Input
        attr_accessor repo: untyped

        attr_accessor collection: untyped

        attr_accessor rkey: untyped

        attr_accessor validate: untyped

        attr_accessor record: untyped

        attr_accessor swapRecord: untyped

        attr_accessor swapCommit: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor uri: untyped

        attr_accessor cid: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoRepoRebaserepo
    module RebaseRepo
      class Input
        attr_accessor repo: untyped

        attr_accessor swapCommit: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoRepoUploadblob
    module UploadBlob
      class Output
        attr_accessor blob: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoServerCreateaccount
    module CreateAccount
      class Input
        attr_accessor email: untyped

        attr_accessor handle: untyped

        attr_accessor did: untyped

        attr_accessor inviteCode: untyped

        attr_accessor password: untyped

        attr_accessor recoveryKey: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor accessJwt: untyped

        attr_accessor refreshJwt: untyped

        attr_accessor handle: untyped

        attr_accessor did: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoServerCreateapppassword
    module CreateAppPassword
      class Input
        attr_accessor name: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[untyped, untyped]
      end
    end
  end

  module ComAtprotoServerCreateinvitecode
    module CreateInviteCode
      class Input
        attr_accessor useCount: untyped

        attr_accessor forAccount: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor code: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoServerCreateinvitecodes
    module CreateInviteCodes
      class Input
        attr_accessor codeCount: untyped

        attr_accessor useCount: untyped

        attr_accessor forAccounts: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor codes: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoServerCreatesession
    module CreateSession
      class Input
        attr_accessor identifier: untyped

        attr_accessor password: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor accessJwt: untyped

        attr_accessor refreshJwt: untyped

        attr_accessor handle: untyped

        attr_accessor did: untyped

        attr_accessor email: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoServerDeleteaccount
    module DeleteAccount
      class Input
        attr_accessor did: untyped

        attr_accessor password: untyped

        attr_accessor token: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoServerDeletesession
    module DeleteSession
    end
  end

  module ComAtprotoServerDescribeserver
    module DescribeServer
      class Output
        attr_accessor inviteCodeRequired: untyped

        attr_accessor availableUserDomains: untyped

        attr_accessor links: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoServerGetaccountinvitecodes
    module GetAccountInviteCodes
      class Input
        attr_accessor includeUsed: untyped

        attr_accessor createAvailable: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor codes: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoServerGetsession
    module GetSession
      class Output
        attr_accessor handle: untyped

        attr_accessor did: untyped

        attr_accessor email: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoServerListapppasswords
    module ListAppPasswords
      class Output
        attr_accessor passwords: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoServerRefreshsession
    module RefreshSession
      class Output
        attr_accessor accessJwt: untyped

        attr_accessor refreshJwt: untyped

        attr_accessor handle: untyped

        attr_accessor did: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoServerRequestaccountdelete
    module RequestAccountDelete
    end
  end

  module ComAtprotoServerRequestpasswordreset
    module RequestPasswordReset
      class Input
        attr_accessor email: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoServerResetpassword
    module ResetPassword
      class Input
        attr_accessor token: untyped

        attr_accessor password: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoServerRevokeapppassword
    module RevokeAppPassword
      class Input
        attr_accessor name: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoSyncGetblob
    module GetBlob
      class Input
        attr_accessor did: untyped

        attr_accessor cid: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoSyncGetblocks
    module GetBlocks
      class Input
        attr_accessor did: untyped

        attr_accessor cids: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoSyncGetcheckout
    module GetCheckout
      class Input
        attr_accessor did: untyped

        attr_accessor commit: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoSyncGetcommitpath
    module GetCommitPath
      class Input
        attr_accessor did: untyped

        attr_accessor latest: untyped

        attr_accessor earliest: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor commits: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoSyncGethead
    module GetHead
      class Input
        attr_accessor did: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor root: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoSyncGetrecord
    module GetRecord
      class Input
        attr_accessor did: untyped

        attr_accessor collection: untyped

        attr_accessor rkey: untyped

        attr_accessor commit: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoSyncGetrepo
    module GetRepo
      class Input
        attr_accessor did: untyped

        attr_accessor earliest: untyped

        attr_accessor latest: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoSyncListblobs
    module ListBlobs
      class Input
        attr_accessor did: untyped

        attr_accessor latest: untyped

        attr_accessor earliest: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cids: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoSyncListrepos
    module ListRepos
      class Input
        attr_accessor limit: untyped

        attr_accessor cursor: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end

      class Output
        attr_accessor cursor: untyped

        attr_accessor repos: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoSyncNotifyofupdate
    module NotifyOfUpdate
      class Input
        attr_accessor hostname: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end

  module ComAtprotoSyncRequestcrawl
    module RequestCrawl
      class Input
        attr_accessor hostname: untyped

        def self.from_hash: (untyped hash) -> untyped

        def to_h: () -> ::Hash[::String, untyped]
      end
    end
  end
end
