# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::CBOR; end
module ::CBOR::Unpacker; end
module ::EM; end
module ::Faye::WebSocket::Client; end
